custom:
  clash_rule_base: https://raw.githubusercontent.com/MuXia-0326/rule/master/clash/clash-rule/forcerule.yml

  proxy_groups:
    - { name: Proxies, type: url-test, rule: [ '.*' ], url: http://www.gstatic.com/generate_204, interval: 300, tolerance: 100, timeout: 5 }

  rulesets:
    - { ruleset: '[]GEOIP,LAN', group: 'DIRECT' }
    - { ruleset: '[]GEOIP,CN', group: 'DIRECT' }
    - { ruleset: '[]MATCH', group: 'Proxies' }
