name: My Workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install dependencies
              run: |
                  npm install mysql

            - name: Run a script
              run: |
                  node -e "
                  var mysql      = require('mysql');
                  var connection = mysql.createConnection({
                    host     : '${{ secrets.MYSQL_HOST }}',
                    user     : '${{ secrets.MYSQL_USER }}',
                    password : '${{ secrets.MYSQL_PASSWORD }}',
                    database : '${{ secrets.MYSQL_DB }}'
                  });

                  connection.connect();

                  connection.query('SELECT * FROM sys_menu', function (error, results, fields) {
                    if (error) throw error;
                    console.log(results);
                  });

                  connection.end();
                  "
